### ISSUE TITLE
NotImplementedError on Windows10

### ISSUE THREAD

**Issue by gakadam** [terhorst/rstviewer#1]
I get NotImplementedError.

I am using windows 10, PowerShell and Anaconda (python 3.6) 64 bit.

Error:

```
Traceback (most recent call last):
  File "c:\programdata\anaconda3\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)

  File "c:\programdata\anaconda3\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)

  File "C:\ProgramData\Anaconda3\Scripts\rstviewer.exe\__main__.py", line 9, in <module>

  File "c:\programdata\anaconda3\lib\site-packages\rstviewer\rstviewer.py", line 197, in main
    loop.run_until_complete(tasks)

  File "c:\programdata\anaconda3\lib\asyncio\base_events.py", line 468, in run_until_complete
    return future.result()

  File "c:\programdata\anaconda3\lib\site-packages\rstviewer\rstviewer.py", line 32, in update_html
    "rst2html5 {} {}".format(rstfile, dest))

  File "c:\programdata\anaconda3\lib\asyncio\subprocess.py", line 210, in create_subprocess_shell
    stderr=stderr, **kwds)

  File "c:\programdata\anaconda3\lib\asyncio\base_events.py", line 1162, in subprocess_shell
    protocol, cmd, True, stdin, stdout, stderr, bufsize, **kwargs)

  File "c:\programdata\anaconda3\lib\asyncio\coroutines.py", line 212, in coro
    res = func(*args, **kw)

  File "c:\programdata\anaconda3\lib\asyncio\base_events.py", line 341, in _make_subprocess_transport

    raise NotImplementedError

NotImplementedError
```

**Comment by terhorst** [comment]
Thanks for reporting. Should be fixed in v0.0.4.1. Unfortunately I do not have a Windows machine to test on, so please let me know if you run into problems.
